// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjazflwqntmyxyntudta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqYXpmbHdxbnRteXh5bnR1ZHRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MTgwOTgsImV4cCI6MjA2OTI5NDA5OH0.bGV5MHEXKA7TLTbtc4_0zhnTSVTu6s0Z7C96aj8h0d4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});